defaults: &defaults
  host: localhost
  port: 27017

development:
  <<: *defaults
  database: locomotive_dev

test:
  <<: *defaults
  database: locomotive_test

# set these environment variables on your prod server
production:
  # heroku
   uri: mongodb://admin:helenandpedro@paulo.mongohq.com:10098/app17562477 
