defaults: &defaults
  host: localhost
  port: 27017
  # slaves:
  #   - host: slave1.local
  #     port: 27018
  #   - host: slave2.local
  #     port: 27019

development:
  <<: *defaults
  database: locomotive_dev

test:
  <<: *defaults
  database: locomotive_test

# set these environment variables on your prod server
production:
  # heroku
   uri: mongodb://heroku:81c03c1fa4fe1a7788106d0fc537e392@paulo.mongohq.com:10098/app17562477 
